[theme]
base="light"
primaryColor="#0056B3"
backgroundColor="#F8FAFC"
secondaryBackgroundColor="#FFFFFF"
textColor="#0F172A"
font="sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true